import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/Providers";
import Footer from "@/components/shared/Footer";
import Navbar from "../components/shared/Navbar";
import { Toaster } from "sonner";
import { getServerSession } from "next-auth";
import { authOptions } from "@/utils/authOptions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "iRepair",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session: any = await getServerSession(authOptions);
  // console.log("session", session);
  // const { username, email, role } = session;
  // console.log("username", username);

  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          <Toaster />
          <Navbar hasSider 
          // session={session ? true : false}
           />
          {children}
          <Footer />
        </body>
      </html>
    </Providers>
  );
}
